networks:
  dev:

services:
  backend:
    build: ./backend-go
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      dev:
        aliases:
          - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      dev: