FROM golang:1.21-alpine

# Устанавливаем air для горячей перезагрузки
RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

# Копируем только файлы зависимостей для начала
COPY go.mod go.sum ./
RUN go mod download

# Остальные файлы будут смонтированы через Docker Compose

# Настройка hot-reload
CMD ["air", "-c", ".air.toml"] 